DROP TABLE IF EXISTS CONCEPT;
DROP TABLE IF EXISTS BROADERS;
DROP TABLE IF EXISTS RELATED;

CREATE TABLE CONCEPT
    (ConceptURI    VARCHAR(100)   NOT NULL,
     PrefLabel      VARCHAR(100)   NOT NULL,
     AltLabel       VARCHAR(100),
     ScopeNotes    VARCHAR(500),
     TopConcept    INTEGER DEFAULT '0',
    PRIMARY KEY (ConceptURI));

CREATE TABLE BROADERS
    (ConceptURI        VARCHAR(100)   NOT NULL,
     BroaderThanURI    VARCHAR(100)   NOT NULL,
    PRIMARY KEY (ConceptURI, BroaderThanURI),
    FOREIGN KEY (ConceptURI) REFERENCES CONCEPT(ConceptURI),
    FOREIGN KEY (BroaderThanURI) REFERENCES CONCEPT(ConceptURI));
    
CREATE TABLE RELATED
    (ConceptURI     VARCHAR(100)   NOT NULL,
     RelatedURI     VARCHAR(100)   NOT NULL,
    PRIMARY KEY (ConceptURI, RelatedURI),
    FOREIGN KEY (ConceptURI) REFERENCES CONCEPT(ConceptURI),
    FOREIGN KEY (RelatedURI) REFERENCES CONCEPT(ConceptURI));


